### ISSUE TITLE
container migration 

### ISSUE THREAD

**Issue by ramy150** [tych0/presentations#1]
hi every one i would to follow the doom migration experience so i copied the script of tycho0
and the checkpoint has done and if i verify in the target node in the /tmp/checkpoint i find the imgs but when the restoring commande run a got this 👍 

root@ubuntu:~# ./migrate2.sh u1 root@172.16.207.166
lxc-checkpoint: criu.c: do_restore: 916 criu process exited 1, output:

lxc-checkpoint: criu.c: __criu_restore: 1221 restore process died
Restoring u1 failed.

i suspect the last line of the script 
thanks to help us

**Comment by tych0** [comment]
Hi,

On Mon, Feb 06, 2017 at 03:44:32PM -0800, ramy150 wrote:
> hi every one i would to follow the doom migration experience so i copied the script of tycho0
> and the checkpoint has done and if i verify in the target node in the /tmp/checkpoint i find the imgs but when the restoring commande run a got this 👍 
> 
> 
> 
> 
> 
> root@ubuntu:~# ./migrate2.sh u1 root@172.16.207.166
> lxc-checkpoint: criu.c: do_restore: 916 criu process exited 1, output:
> 
> lxc-checkpoint: criu.c: __criu_restore: 1221 restore process died
> Restoring u1 failed.

Can you post the output of the checkpoint and restore logs?
(/tmp/checkpoint/{dump,restore}.log).

**Comment by ramy150** [comment]
hi tych0,

 this is two screenshot one from the source (checkpoint) and the other from the destination(restore)


we try also your demo with the move command it works but the problem we try also to reduce the downtime we think in iterative migration but there are more others problem like criu dump



hope you will help us because we are doing that to perform a live iterative migration across clouds in our masters thesis and we chose the lxc/lxd to proceed throw it

thanks

Best regards
ADDAD Rami Akrem

________________________________
De : Tycho Andersen <notifications@github.com>
Envoyé : mardi 7 février 2017 16:09
À : tych0/presentations
Cc : ramy150; Author
Objet : Re: [tych0/presentations] container migration (#1)

Hi,

On Mon, Feb 06, 2017 at 03:44:32PM -0800, ramy150 wrote:
> hi every one i would to follow the doom migration experience so i copied the script of tycho0
> and the checkpoint has done and if i verify in the target node in the /tmp/checkpoint i find the imgs but when the restoring commande run a got this 👍
>
>
>
>
>
> root@ubuntu:~# ./migrate2.sh u1 root@172.16.207.166
> lxc-checkpoint: criu.c: do_restore: 916 criu process exited 1, output:
>
> lxc-checkpoint: criu.c: __criu_restore: 1221 restore process died
> Restoring u1 failed.

Can you post the output of the checkpoint and restore logs?
(/tmp/checkpoint/{dump,restore}.log).

**Comment by tych0** [comment]
Please don't post screenshots (they didn't come through anyway). Please paste the entire contents into the mail, or to a pastebin.

**Comment by ramy150** [comment]
hi tych0,



the target host :

#####################


root@ubuntu:~# cd ../tmp/checkpoint/
root@ubuntu:/tmp/checkpoint# ls
cgroup.img     fdinfo-16.img  fs-3556.img       ip6tables-9.img     pagemap-1541.img          pages-17.img      sigacts-1595.img
core-1532.img  fdinfo-17.img  fs-3557.img       ipcns-shm-10.img    pagemap-1589.img          pages-18.img      sigacts-1627.img
core-1541.img  fdinfo-18.img  fs-3564.img       ipcns-var-10.img    pagemap-1595.img          pages-19.img      sigacts-1699.img
core-1589.img  fdinfo-19.img  fs-3574.img       iptables-9.img      pagemap-1627.img          pages-1.img       sigacts-1702.img
core-1591.img  fdinfo-20.img  fs-3588.img       mm-1532.img         pagemap-1699.img          pages-20.img      sigacts-1703.img
core-1592.img  fdinfo-21.img  fs-3589.img       mm-1541.img         pagemap-1702.img          pages-21.img      sigacts-1716.img
core-1593.img  fdinfo-22.img  fs-3590.img       mm-1589.img         pagemap-1703.img          pages-22.img      sigacts-1722.img
core-1595.img  fdinfo-23.img  fs-468.img        mm-1595.img         pagemap-1716.img          pages-23.img      sigacts-1752.img
core-1627.img  fdinfo-24.img  ghost-file-1.img  mm-1627.img         pagemap-1722.img          pages-24.img      sigacts-1754.img
core-1699.img  fdinfo-25.img  ids-1532.img      mm-1699.img         pagemap-1752.img          pages-25.img      sigacts-1781.img
core-1702.img  fdinfo-26.img  ids-1541.img      mm-1702.img         pagemap-1754.img          pages-26.img      sigacts-1792.img
core-1703.img  fdinfo-2.img   ids-1589.img      mm-1703.img         pagemap-1781.img          pages-27.img      sigacts-1793.img
core-1716.img  fdinfo-3.img   ids-1595.img      mm-1716.img         pagemap-1792.img          pages-28.img      sigacts-1.img
core-1722.img  fdinfo-4.img   ids-1627.img      mm-1722.img         pagemap-1793.img          pages-29.img      sigacts-3550.img
core-1752.img  fdinfo-5.img   ids-1699.img      mm-1752.img         pagemap-1.img             pages-2.img       sigacts-3556.img
core-1754.img  fdinfo-6.img   ids-1702.img      mm-1754.img         pagemap-3550.img          pages-30.img      sigacts-3557.img
core-1781.img  fdinfo-7.img   ids-1703.img      mm-1781.img         pagemap-3556.img          pages-31.img      sigacts-3564.img
core-1792.img  fdinfo-8.img   ids-1716.img      mm-1792.img         pagemap-3557.img          pages-3.img       sigacts-3574.img
core-1793.img  fdinfo-9.img   ids-1722.img      mm-1793.img         pagemap-3564.img          pages-4.img       sigacts-3588.img
core-1.img     filelocks.img  ids-1752.img      mm-1.img            pagemap-3574.img          pages-5.img       sigacts-3589.img
core-3550.img  fs-1532.img    ids-1754.img      mm-3550.img         pagemap-3588.img          pages-6.img       sigacts-3590.img
core-3556.img  fs-1541.img    ids-1781.img      mm-3556.img         pagemap-3589.img          pages-7.img       sigacts-468.img
core-3557.img  fs-1589.img    ids-1792.img      mm-3557.img         pagemap-3590.img          pages-8.img       signalfd.img
core-3564.img  fs-1595.img    ids-1793.img      mm-3564.img         pagemap-468.img           pages-9.img       tcp-stream-4c10f.img
core-3574.img  fs-1627.img    ids-1.img         mm-3574.img         pagemap-shmem-0.img       pipes-data.img    tcp-stream-4c83c.img
core-3588.img  fs-1699.img    ids-3550.img      mm-3588.img         pagemap-shmem-310547.img  pipes.img         tmpfs-dev-100.tar.gz.img
core-3589.img  fs-1702.img    ids-3556.img      mm-3589.img         pagemap-shmem-310559.img  pstree.img        tmpfs-dev-43.tar.gz.img
core-3590.img  fs-1703.img    ids-3557.img      mm-3590.img         pagemap-shmem-32769.img   reg-files.img     tmpfs-dev-96.tar.gz.img
core-468.img   fs-1716.img    ids-3564.img      mm-468.img          pagemap-shmem-65538.img   remap-fpath.img   tmpfs-dev-97.tar.gz.img
dump.log       fs-1722.img    ids-3574.img      mountpoints-12.img  pagemap-shmem-98307.img   restore.log       tmpfs-dev-98.tar.gz.img
eventpoll.img  fs-1752.img    ids-3588.img      netdev-9.img        pages-10.img              route6-9.img      tmpfs-dev-99.tar.gz.img
fdinfo-10.img  fs-1754.img    ids-3589.img      netlinksk.img       pages-11.img              route-9.img       tty.img
fdinfo-11.img  fs-1781.img    ids-3590.img      netns-9.img         pages-12.img              rule-9.img        tty-info.img
fdinfo-12.img  fs-1792.img    ids-468.img       netns-ct-9.img      pages-13.img              seccomp.img       unixsk.img
fdinfo-13.img  fs-1793.img    ifaddr-9.img      netns-exp-9.img     pages-14.img              sigacts-1532.img  utsns-11.img
fdinfo-14.img  fs-1.img       inetsk.img        packetsk.img        pages-15.img              sigacts-1541.img
fdinfo-15.img  fs-3550.img    inotify.img       pagemap-1532.img    pages-16.img              sigacts-1589.img
root@ubuntu:/tmp/checkpoint# cd
root@ubuntu:~# ls
tet.txt
root@ubuntu:~# cat tet.txt
 lxc-checkpoint 20160207165019.812 ERROR    lxc_criu - criu.c:do_restore:916 - criu process exited 1, output:

 lxc-checkpoint 20160207165020.320 ERROR    lxc_criu - criu.c:__criu_restore:1221 - restore process died
 lxc-checkpoint 20160207165126.936 ERROR    lxc_criu - criu.c:do_restore:916 - criu process exited 1, output:

 lxc-checkpoint 20160207165127.445 ERROR    lxc_criu - criu.c:__criu_restore:1221 - restore process died
root@ubuntu:~#






########################################################################



the source host :



Croot@ubuntu:~cd ../tmp/checkpoint
root@ubuntu:/tmp/checkpoint# ls
cgroup.img     fdinfo-16.img  fs-3556.img       ip6tables-9.img     pagemap-1541.img          pages-17.img      sigacts-1627.img
core-1532.img  fdinfo-17.img  fs-3557.img       ipcns-shm-10.img    pagemap-1589.img          pages-18.img      sigacts-1699.img
core-1541.img  fdinfo-18.img  fs-3564.img       ipcns-var-10.img    pagemap-1595.img          pages-19.img      sigacts-1702.img
core-1589.img  fdinfo-19.img  fs-3574.img       iptables-9.img      pagemap-1627.img          pages-1.img       sigacts-1703.img
core-1591.img  fdinfo-20.img  fs-3588.img       mm-1532.img         pagemap-1699.img          pages-20.img      sigacts-1716.img
core-1592.img  fdinfo-21.img  fs-3589.img       mm-1541.img         pagemap-1702.img          pages-21.img      sigacts-1722.img
core-1593.img  fdinfo-22.img  fs-3590.img       mm-1589.img         pagemap-1703.img          pages-22.img      sigacts-1752.img
core-1595.img  fdinfo-23.img  fs-468.img        mm-1595.img         pagemap-1716.img          pages-23.img      sigacts-1754.img
core-1627.img  fdinfo-24.img  ghost-file-1.img  mm-1627.img         pagemap-1722.img          pages-24.img      sigacts-1781.img
core-1699.img  fdinfo-25.img  ids-1532.img      mm-1699.img         pagemap-1752.img          pages-25.img      sigacts-1792.img
core-1702.img  fdinfo-26.img  ids-1541.img      mm-1702.img         pagemap-1754.img          pages-26.img      sigacts-1793.img
core-1703.img  fdinfo-2.img   ids-1589.img      mm-1703.img         pagemap-1781.img          pages-27.img      sigacts-1.img
core-1716.img  fdinfo-3.img   ids-1595.img      mm-1716.img         pagemap-1792.img          pages-28.img      sigacts-3550.img
core-1722.img  fdinfo-4.img   ids-1627.img      mm-1722.img         pagemap-1793.img          pages-29.img      sigacts-3556.img
core-1752.img  fdinfo-5.img   ids-1699.img      mm-1752.img         pagemap-1.img             pages-2.img       sigacts-3557.img
core-1754.img  fdinfo-6.img   ids-1702.img      mm-1754.img         pagemap-3550.img          pages-30.img      sigacts-3564.img
core-1781.img  fdinfo-7.img   ids-1703.img      mm-1781.img         pagemap-3556.img          pages-31.img      sigacts-3574.img
core-1792.img  fdinfo-8.img   ids-1716.img      mm-1792.img         pagemap-3557.img          pages-3.img       sigacts-3588.img
core-1793.img  fdinfo-9.img   ids-1722.img      mm-1793.img         pagemap-3564.img          pages-4.img       sigacts-3589.img
core-1.img     filelocks.img  ids-1752.img      mm-1.img            pagemap-3574.img          pages-5.img       sigacts-3590.img
core-3550.img  fs-1532.img    ids-1754.img      mm-3550.img         pagemap-3588.img          pages-6.img       sigacts-468.img
core-3556.img  fs-1541.img    ids-1781.img      mm-3556.img         pagemap-3589.img          pages-7.img       signalfd.img
core-3557.img  fs-1589.img    ids-1792.img      mm-3557.img         pagemap-3590.img          pages-8.img       tcp-stream-4c10f.img
core-3564.img  fs-1595.img    ids-1793.img      mm-3564.img         pagemap-468.img           pages-9.img       tcp-stream-4c83c.img
core-3574.img  fs-1627.img    ids-1.img         mm-3574.img         pagemap-shmem-0.img       pipes-data.img    tmpfs-dev-100.tar.gz.img
core-3588.img  fs-1699.img    ids-3550.img      mm-3588.img         pagemap-shmem-310547.img  pipes.img         tmpfs-dev-43.tar.gz.img
core-3589.img  fs-1702.img    ids-3556.img      mm-3589.img         pagemap-shmem-310559.img  pstree.img        tmpfs-dev-96.tar.gz.img
core-3590.img  fs-1703.img    ids-3557.img      mm-3590.img         pagemap-shmem-32769.img   reg-files.img     tmpfs-dev-97.tar.gz.img
core-468.img   fs-1716.img    ids-3564.img      mm-468.img          pagemap-shmem-65538.img   remap-fpath.img   tmpfs-dev-98.tar.gz.img
dump.log       fs-1722.img    ids-3574.img      mountpoints-12.img  pagemap-shmem-98307.img   route6-9.img      tmpfs-dev-99.tar.gz.img
eventpoll.img  fs-1752.img    ids-3588.img      netdev-9.img        pages-10.img              route-9.img       tty.img
fdinfo-10.img  fs-1754.img    ids-3589.img      netlinksk.img       pages-11.img              rule-9.img        tty-info.img
fdinfo-11.img  fs-1781.img    ids-3590.img      netns-9.img         pages-12.img              seccomp.img       unixsk.img
fdinfo-12.img  fs-1792.img    ids-468.img       netns-ct-9.img      pages-13.img              sigacts-1532.img  utsns-11.img
fdinfo-13.img  fs-1793.img    ifaddr-9.img      netns-exp-9.img     pages-14.img              sigacts-1541.img
fdinfo-14.img  fs-1.img       inetsk.img        packetsk.img        pages-15.img              sigacts-1589.img
fdinfo-15.img  fs-3550.img    inotify.img       pagemap-1532.img    pages-16.img              sigacts-1595.img
root@ubuntu:/tmp/checkpoint# cd
root@ubuntu:~# cat te.txt
 lxc-checkpoint u1 20160207164932.561 ERROR    lxc_criu - criu.c:do_dump:1125 - dump failed with 1
 lxc-checkpoint u1 20160207164932.561 ERROR    lxc_criu - criu.c:do_dump:1139 - criu output:
 lxc-checkpoint u1 20160207165123.668 ERROR    lxc_criu - criu.c:do_dump:1125 - dump failed with 1
 lxc-checkpoint u1 20160207165123.668 ERROR    lxc_criu - criu.c:do_dump:1139 - criu output:
root@ubuntu:~#










Best regards,


________________________________
De : Tycho Andersen <notifications@github.com>
Envoyé : mardi 7 février 2017 17:14
À : tych0/presentations
Cc : ramy150; Author
Objet : Re: [tych0/presentations] container migration (#1)


Please don't post screenshots (they didn't come through anyway). Please paste the entire contents into the mail, or to a pastebin.

**Comment by tych0** [comment]
What I'm after is the *content* of the restore.log and dump.log files.

**Comment by ramy150** [comment]
hi tych0,

i'm sorry my friend but i don't know to get it

i try to the -o option in lxc command and to get the output in a file text

is it like that or i should proceed on other manner

really sorry for this lack of information

Best regards


________________________________
De : Tycho Andersen <notifications@github.com>
Envoyé : mardi 7 février 2017 17:19
À : tych0/presentations
Cc : ramy150; Author
Objet : Re: [tych0/presentations] container migration (#1)


What I'm after is the content of the restore.log and dump.log files.

**Comment by tych0** [comment]
On Tue, Feb 07, 2017 at 09:25:21AM -0800, ramy150 wrote:
> hi tych0,
> 
> i'm sorry my friend but i don't know to get it
> 
> i try to the -o option in lxc command and to get the output in a file text
> 
> is it like that or i should proceed on other manner
> 
> really sorry for this lack of information

The file is in the directory ls output you just posted, called
"restore.log". Just cat it as well.

**Comment by ramy150** [comment]
hi tych0,



the target host


cat dump.log
Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
Warn  (criu/arch/x86/crtools.c:138): Will restore 69251 with interrupted system call
Warn  (criu/arch/x86/crtools.c:138): Will restore 72607 with interrupted system call
Warn  (criu/arch/x86/crtools.c:138): Will restore 69153 with interrupted system call
Warn  (criu/arch/x86/crtools.c:138): Will restore 71108 with interrupted system call
tar: ./udev/control: socket ignored
tar: ./log: socket ignored
Error (criu/tty.c:382): tty: Found slave peer index 0 without correspond master peer
Error (criu/cr-dump.c:1636): Dumping FAILED.




cat restore.log
(00.000091) Version: 2.10 (gitid v2.10-2-gcf72ced)
(00.004945) No inventory.img image
(00.005022) Error (criu/util.c:552): Can't read link of fd -404: No such file or directory
(00.005034) Error (criu/protobuf.c:75): Unexpected EOF on (null)


###########################################################
the source host

cat dump.log
Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
Warn  (criu/arch/x86/crtools.c:138): Will restore 69251 with interrupted system call
Warn  (criu/arch/x86/crtools.c:138): Will restore 72607 with interrupted system call
Warn  (criu/arch/x86/crtools.c:138): Will restore 69153 with interrupted system call
Warn  (criu/arch/x86/crtools.c:138): Will restore 71108 with interrupted system call
tar: ./udev/control: socket ignored
tar: ./log: socket ignored
Error (criu/tty.c:382): tty: Found slave peer index 0 without correspond master peer
Error (criu/cr-dump.c:1636): Dumping FAILED.


________________________________
De : Tycho Andersen <notifications@github.com>
Envoyé : mardi 7 février 2017 17:27
À : tych0/presentations
Cc : ramy150; Author
Objet : Re: [tych0/presentations] container migration (#1)

On Tue, Feb 07, 2017 at 09:25:21AM -0800, ramy150 wrote:
> hi tych0,
>
> i'm sorry my friend but i don't know to get it
>
> i try to the -o option in lxc command and to get the output in a file text
>
> is it like that or i should proceed on other manner
>
> really sorry for this lack of information

The file is in the directory ls output you just posted, called
"restore.log". Just cat it as well.

**Comment by tych0** [comment]
On Tue, Feb 07, 2017 at 09:33:24AM -0800, ramy150 wrote:
> hi tych0,
> 
> 
> 
> the target host
> 
> 
> cat dump.log
> Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
> Warn  (criu/arch/x86/crtools.c:138): Will restore 69251 with interrupted system call
> Warn  (criu/arch/x86/crtools.c:138): Will restore 72607 with interrupted system call
> Warn  (criu/arch/x86/crtools.c:138): Will restore 69153 with interrupted system call
> Warn  (criu/arch/x86/crtools.c:138): Will restore 71108 with interrupted system call
> tar: ./udev/control: socket ignored
> tar: ./log: socket ignored
> Error (criu/tty.c:382): tty: Found slave peer index 0 without correspond master peer
> Error (criu/cr-dump.c:1636): Dumping FAILED.
> 
> 
> 
> 
> cat restore.log
> (00.000091) Version: 2.10 (gitid v2.10-2-gcf72ced)
> (00.004945) No inventory.img image
> (00.005022) Error (criu/util.c:552): Can't read link of fd -404: No such file or directory
> (00.005034) Error (criu/protobuf.c:75): Unexpected EOF on (null)
> 
> 
> ###########################################################
> the source host
> 
> cat dump.log
> Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
> Warn  (criu/arch/x86/crtools.c:138): Will restore 69251 with interrupted system call
> Warn  (criu/arch/x86/crtools.c:138): Will restore 72607 with interrupted system call
> Warn  (criu/arch/x86/crtools.c:138): Will restore 69153 with interrupted system call
> Warn  (criu/arch/x86/crtools.c:138): Will restore 71108 with interrupted system call
> tar: ./udev/control: socket ignored
> tar: ./log: socket ignored
> Error (criu/tty.c:382): tty: Found slave peer index 0 without correspond master peer
> Error (criu/cr-dump.c:1636): Dumping FAILED.

Looks like you have a console set up. Did you set lxc.console = none
in your config?

**Comment by ramy150** [comment]
hi tych0,



cat config
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template: -r trusty -a amd64
# Template script checksum (SHA-1): 704a37e3ce689db94dd1c1a02eae680a00cb5a82
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf

# Container specific configuration
lxc.rootfs = /var/lib/lxc/u1/rootfs
lxc.rootfs.backend = dir
lxc.utsname = u1
lxc.arch = amd64

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:13:b7:8e
# hax for criu
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm

________________________________
De : Tycho Andersen <notifications@github.com>
Envoyé : mardi 7 février 2017 17:36
À : tych0/presentations
Cc : ramy150; Author
Objet : Re: [tych0/presentations] container migration (#1)

On Tue, Feb 07, 2017 at 09:33:24AM -0800, ramy150 wrote:
> hi tych0,
>
>
>
> the target host
>
>
> cat dump.log
> Warn (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
> Warn (criu/arch/x86/crtools.c:138): Will restore 69251 with interrupted system call
> Warn (criu/arch/x86/crtools.c:138): Will restore 72607 with interrupted system call
> Warn (criu/arch/x86/crtools.c:138): Will restore 69153 with interrupted system call
> Warn (criu/arch/x86/crtools.c:138): Will restore 71108 with interrupted system call
> tar: ./udev/control: socket ignored
> tar: ./log: socket ignored
> Error (criu/tty.c:382): tty: Found slave peer index 0 without correspond master peer
> Error (criu/cr-dump.c:1636): Dumping FAILED.
>
>
>
>
> cat restore.log
> (00.000091) Version: 2.10 (gitid v2.10-2-gcf72ced)
> (00.004945) No inventory.img image
> (00.005022) Error (criu/util.c:552): Can't read link of fd -404: No such file or directory
> (00.005034) Error (criu/protobuf.c:75): Unexpected EOF on (null)
>
>
> ###########################################################
> the source host
>
> cat dump.log
> Warn (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
> Warn (criu/arch/x86/crtools.c:138): Will restore 69251 with interrupted system call
> Warn (criu/arch/x86/crtools.c:138): Will restore 72607 with interrupted system call
> Warn (criu/arch/x86/crtools.c:138): Will restore 69153 with interrupted system call
> Warn (criu/arch/x86/crtools.c:138): Will restore 71108 with interrupted system call
> tar: ./udev/control: socket ignored
> tar: ./log: socket ignored
> Error (criu/tty.c:382): tty: Found slave peer index 0 without correspond master peer
> Error (criu/cr-dump.c:1636): Dumping FAILED.

Looks like you have a console set up. Did you set lxc.console = none
in your config?

**Comment by tych0** [comment]
On Tue, Feb 07, 2017 at 09:41:39AM -0800, ramy150 wrote:
> hi tych0,
> 
> 
> 
> cat config
> # Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
> # Parameters passed to the template: -r trusty -a amd64
> # Template script checksum (SHA-1): 704a37e3ce689db94dd1c1a02eae680a00cb5a82
> # For additional config options, please look at lxc.container.conf(5)
> 
> # Uncomment the following line to support nesting containers:
> #lxc.include = /usr/share/lxc/config/nesting.conf
> # (Be aware this has security implications)
> 
> 
> # Common configuration
> lxc.include = /usr/share/lxc/config/ubuntu.common.conf
> 
> # Container specific configuration
> lxc.rootfs = /var/lib/lxc/u1/rootfs
> lxc.rootfs.backend = dir
> lxc.utsname = u1
> lxc.arch = amd64
> 
> # Network configuration
> lxc.network.type = veth
> lxc.network.link = lxcbr0
> lxc.network.flags = up
> lxc.network.hwaddr = 00:16:3e:13:b7:8e
> # hax for criu
> lxc.console = none
> lxc.tty = 0
> lxc.cgroup.devices.deny = c 5:1 rwm

Hmm. And you've restarted the container after this?

**Comment by ramy150** [comment]
hi tych0,


yes i did it, but i encountered the same issues, criu fails to restore. I'm currently using the 2.10 version of criu. which version would you recommand me using?


Thank you


________________________________
De : Tycho Andersen <notifications@github.com>
Envoyé : mardi 7 février 2017 17:43
À : tych0/presentations
Cc : ramy150; Author
Objet : Re: [tych0/presentations] container migration (#1)

On Tue, Feb 07, 2017 at 09:41:39AM -0800, ramy150 wrote:
> hi tych0,
>
>
>
> cat config
> # Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
> # Parameters passed to the template: -r trusty -a amd64
> # Template script checksum (SHA-1): 704a37e3ce689db94dd1c1a02eae680a00cb5a82
> # For additional config options, please look at lxc.container.conf(5)
>
> # Uncomment the following line to support nesting containers:
> #lxc.include = /usr/share/lxc/config/nesting.conf
> # (Be aware this has security implications)
>
>
> # Common configuration
> lxc.include = /usr/share/lxc/config/ubuntu.common.conf
>
> # Container specific configuration
> lxc.rootfs = /var/lib/lxc/u1/rootfs
> lxc.rootfs.backend = dir
> lxc.utsname = u1
> lxc.arch = amd64
>
> # Network configuration
> lxc.network.type = veth
> lxc.network.link = lxcbr0
> lxc.network.flags = up
> lxc.network.hwaddr = 00:16:3e:13:b7:8e
> # hax for criu
> lxc.console = none
> lxc.tty = 0
> lxc.cgroup.devices.deny = c 5:1 rwm

Hmm. And you've restarted the container after this?

**Comment by ramy150** [comment]
Good afternoon,
I finally managed to migrate the container to a different host, but i noticed that the migration process wasn't stateful.
The video game froze for about 4 or 5 seconds
do you think that there is a way to make this process seamless, and prevent data loss?
We saw that you do it in a slide of 8 pages
Please if you could help us it will be great
Thanks a lot


On Feb 7, 2017, at 7:43 PM, Tycho Andersen <notifications@github.com<mailto:notifications@github.com>> wrote:

On Tue, Feb 07, 2017 at 09:41:39AM -0800, ramy150 wrote:
> hi tych0,
>
>
>
> cat config
> # Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
> # Parameters passed to the template: -r trusty -a amd64
> # Template script checksum (SHA-1): 704a37e3ce689db94dd1c1a02eae680a00cb5a82
> # For additional config options, please look at lxc.container.conf(5)
>
> # Uncomment the following line to support nesting containers:
> #lxc.include = /usr/share/lxc/config/nesting.conf
> # (Be aware this has security implications)
>
>
> # Common configuration
> lxc.include = /usr/share/lxc/config/ubuntu.common.conf
>
> # Container specific configuration
> lxc.rootfs = /var/lib/lxc/u1/rootfs
> lxc.rootfs.backend = dir
> lxc.utsname = u1
> lxc.arch = amd64
>
> # Network configuration
> lxc.network.type = veth
> lxc.network.link = lxcbr0
> lxc.network.flags = up
> lxc.network.hwaddr = 00:16:3e:13:b7:8e
> # hax for criu
> lxc.console = none
> lxc.tty = 0
> lxc.cgroup.devices.deny = c 5:1 rwm

Hmm. And you've restarted the container after this?

**Comment by ramy150** [comment]
This is the demo which I 'm talking about 
Thanks a lot





Sent from my iPhone

**Comment by tych0** [comment]
On Tue, Feb 07, 2017 at 12:07:13PM -0800, ramy150 wrote:
> Good afternoon,
> I finally managed to migrate the container to a different host, but i noticed that the migration process wasn't stateful.

Heh. It is, because the video game resumes, right?

> The video game froze for about 4 or 5 seconds
> do you think that there is a way to make this process seamless, and prevent data loss?

Lots of ways; this is a very difficult problem though. See articles on
pre-copy and post-copy work in CRIU.

> We saw that you do it in a slide of 8 pages
> Please if you could help us it will be great
> Thanks a lot
> 
>

**Comment by tych0** [comment]
On Tue, Feb 07, 2017 at 12:08:22PM -0800, ramy150 wrote:
> This is the demo which I 'm talking about 

Hmm. The link didn't come through.
